// scripts/local-env.mjs
// Writes apps/generator/.env.local from the running local Supabase stack.
// Variable names match what the Vercel Supabase integration injects, so the
// app code has one set of names for both environments.
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const out = resolve("apps/generator/.env.local");

let raw;
try {
  raw = execFileSync("supabase", ["status", "-o", "env"], { encoding: "utf8" });
} catch {
  console.error("Local Supabase is not running. Start it with `pnpm db:start`.");
  process.exit(1);
}

const status = Object.fromEntries(
  raw
    .split("\n")
    .filter((line) => line.includes("="))
    .map((line) => {
      const [key, ...rest] = line.split("=");
      return [key.trim(), rest.join("=").trim().replace(/^"|"$/g, "")];
    }),
);

const pick = (...names) => {
  for (const name of names) if (status[name]) return status[name];
  throw new Error(`supabase status did not report ${names.join(" or ")}`);
};

const vars = {
  POSTGRES_URL: pick("DB_URL"),
  POSTGRES_URL_NON_POOLING: pick("DB_URL"),
  SUPABASE_URL: pick("API_URL"),
  SUPABASE_PUBLISHABLE_KEY: pick("PUBLISHABLE_KEY", "ANON_KEY"),
  SUPABASE_SECRET_KEY: pick("SECRET_KEY", "SERVICE_ROLE_KEY"),
};

if (process.argv.includes("--studio")) {
  console.log(pick("STUDIO_URL"));
  process.exit(0);
}

writeFileSync(
  out,
  `# Generated by \`pnpm db:env\` from the local Supabase stack. Do not commit.\n` +
    Object.entries(vars)
      .map(([k, v]) => `${k}=${v}`)
      .join("\n") +
    "\n",
);
console.log(`Wrote ${out}`);
